sudo: required

# skip language installation steps for docker builds
install: true

services:
    - docker

env:
  # Specify which Dockerfiles to add to the build matrix
  - TAG=ubuntu-trusty

script:
  # replace TAG dashes with slashes to get directory
  - cd fpm/$(sed 's/-/\//g' <<< $TAG)
  - docker build -t colinhoglund/fpm:$TAG .
