sudo: required

# skip language installation steps for docker builds
install: true

services:
    - docker

env:
    - TEST: centos/7/Dockerfile
    - TEST: centos/7/build_scripts/build_python
    - TEST: ubuntu/trusty/Dockerfile
    - TEST: ubuntu/trusty/build_scripts/build_python
    - TEST: ubuntu/trusty/build_scripts/build_uwsgi

script: ./tests.sh
